#!/usr/bin/env python3

import json
import subprocess


def main():
    output = subprocess.check_output(['juju', 'status', '--format', 'json'])
    status = json.loads(output.decode('utf-8'))
    model = status['model']
    machines = tuple(status['machines'].keys())
    applications = tuple(status['applications'].keys())

    if not (machines or applications):
        return

    print('model {name} on {controller} ({cloud})'.format(**model))
    if machines:
        print('  machines: {}'.format(', '.join(machines)))
    if applications:
        print('  applications: {}'.format(', '.join(applications)))
    answer = input('remove everything? [n] ')
    if answer.lower() != 'y':
        return

    for machine in machines:
        subprocess.check_call(['juju', 'remove-machine', '--force', machine])
    for application in applications:
        subprocess.check_call(['juju', 'remove-application', application])


if __name__ == '__main__':
    main()
