#!/bin/sh

# Connect via SSH to a LXD, being it stopped or started.

set -e

usage() {
    cmd=`basename $0`
    echo "Usage:\n  $cmd <name>"
    echo "For instance:\n  $cmd mycontainer"
    exit 1
}

[ "$#" != 1 ] && usage

name=$1
status=`lxc info $name | grep -i status | awk '{print tolower($2)}'`
if [ "$status" = "running" ]; then
    echo "$name is running"
else
    echo "starting $name"
    lxc start $name
    sleep 5
fi

echo "waiting for ip address"
address=
while [ -z "$address" ]; do
    address=`lxc info $name | grep eth0 | grep -v inet6 | head -1 | awk '{print $3}'`
    sleep 0.2
done

echo "waiting for ability to connect"
while ! ssh -A -t $address true > /dev/null 2>&1; do
    sleep 0.1
done

echo "ssh -A -t $address"
ssh -A -t $address "cd $PWD && echo connected && exec $SHELL"
