#!/bin/bash

# Create an SSH tunnel for accesing the service exposed by the container at the
# given port.

# Save this script in your path, for instance as "lxc-tunnel" and run it
# without arguments for usage instructions.

set -e

usage() {
    cmd=`basename $0`
    echo -e "Usage:\n  $cmd <container> <port>"
    echo -e "For instance:\n  $cmd mycontainer 4247"
    exit 1
}

[[ $# != 2 ]] && usage

name=$1
outport=$2
inport=$(($RANDOM % 10000 + 5000))
host=`lxc info $name | grep eth0 | grep -v inet6 | head -1 | awk '{print $3}'`

echo access service at http://`hostname`.local:$inport/
echo ssh -g -L $inport:$host:$outport $host
ssh -g -L $inport:$host:$outport $host
echo quitting tunnel
